from .estudante import Estudante
from .horarios import Horarios
from .professor import Professor
from .projetos import Projetos
from .universidade import Universidade
from .user import User
from .refresh_token import RefreshToken
from .solicitacoes_vincular import SolicitacaoVincular
from .cronogramas import Cronograma
from .solicitacoes_projetos import SolicitacaoCancelamento